<?php
$this->title = 'Les Personne';
$this->headTitle($this->title);
?>

<?php
$this->tabContainer()->captureStart('tabcontainer', array(), array());
$this->contentPane()->captureStart('tab1', array(), array('title' => 'User Manager'));
?>
<p><a href="<?php
echo $this->url(array('controller' => 'personne',
    'action' => 'ajouter'));
?>">Ajouter une nouvelle Personne</a></p>


<!--<form action="postIt" id="myform">-->

<script type="text/javascript" >    
    var structure = [ 
        { field: 'idpersonne', name: 'CommuneID', width: '50px' },
        { field: 'nom', name : 'Nom', width: '100px' },
        { field: 'date_naissance', name : 'Date naissance', width: '200px'},
        { field: 'phone', name : 'phone', width: '200px'}
    ]; 
</script>


<!--<th>Nom</th>
        <th>Prenom</th>
        <th>Date naissance</th>
        <th>phone</th>
        <th>&nbsp;</th>-->

<span dojoType="dojox.data.QueryReadStore" jsId="idpersonne" url="/v_esp/public/personne/indexjson"></span>
<div id="grid1" data-dojo-id="grid2" dojoType="dojox.grid.DataGrid" 
     data-dojo-props="store:idpersonne,
     structure:'structure'  ,
     clientSort:true,
     rowSelector:'20px'"
     style=" height: 260px;"></div>

<div data-dojo-type="dijit/form/Form" id="modifier" data-dojo-id="myForm"
     encType="multipart/form-data" action="personne/modifier" method="GET">
    <script type="dojo/on" data-dojo-event="submit">
        dojo.require("dojo.NodeList-manipulate");
        var items = grid2.selection.getSelected();
        if(items.length){            
            dojo.forEach(items, function(selectedItem){
                if(selectedItem !== null){
                    attribute = 'idpersonne';
                    var value = grid2.store.getValues(selectedItem, attribute);                    
                    var idpersonne = dojo.query("#id").val(value);
                } 
            }); 
        }
        </script>
    
    <input type="hidden" id="id" name="id"  value="" />
    <button data-dojo-type="dijit/form/Button"             
            type="submit">
        Modifier
        
    </button>
</div>
<?php
echo $this->contentPane()->captureEnd('tab1');
echo $this->tabContainer()->captureEnd('tabcontainer');
?>



