<?php
$this->title = 'Les Personne';
$this->headTitle($this->title);

?>
<p><a href="<?php echo $this->url(array('controller'=>'personne',
        'action'=>'ajouter'));?>">Ajouter une nouvelle Personne</a></p>
<table>
    <tr>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Date naissance</th>
        <th>phone</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach($this->personnes as $personne) : ?>
    <tr>
        <td><?php echo $this->escape($personne->nom);?></td>
        <td><?php echo $this->escape($personne->prenom);?></td>
        <td><?php echo $this->escape($personne->date_naissance);?></td>
        <td><?php echo $this->escape($personne->phone);?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'personne',
                'action'=>'modifier', 'id'=>$personne->idpersonne));?>">Modifier</a>
            <a href="<?php echo $this->url(array('controller'=>'personne',
                'action'=>'supprimer', 'id'=>$personne->idpersonne));?>">Supprimer</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>