<?php
$this->title = 'Les Personne';
$this->headTitle($this->title);
?>

<?php
$this->tabContainer()->captureStart('tabcontainer', array(), array());
$this->contentPane()->captureStart('tab1', array(), array('title' => 'User Manager'));
?>
<p><a href="<?php
echo $this->url(array('controller' => 'personne',
    'action' => 'ajouter'));
?>">Ajouter une nouvelle Personne</a></p>


<!--<form action="postIt" id="myform">-->

<script type="text/javascript" >    
    var structure = [ 
        { field: 'idpersonne', name: 'CommuneID', width: '50px' },
        { field: 'nom', name : 'Nom', width: '100px' },
        { field: 'date_naissance', name : 'Date naissance', width: '200px'},
        { field: 'phone', name : 'phone', width: '200px'}
    ]; 
</script>


<!--<th>Nom</th>
        <th>Prenom</th>
        <th>Date naissance</th>
        <th>phone</th>
        <th>&nbsp;</th>-->

<span dojoType="dojox.data.QueryReadStore" jsId="idpersonne" url="/v_esp/public/personne/indexjson"></span>
<div id="grid1" data-dojo-id="grid2" dojoType="dojox.grid.DataGrid" 
     data-dojo-props="store:idpersonne,
     structure:'structure'  ,
     clientSort:true,
     rowSelector:'20px'"
     style=" height: 260px;"></div>

<div data-dojo-type="dijit/form/Form" id="modifier" data-dojo-id="myForm"
     encType="multipart/form-data" action="personne/modifier" method="GET">
    <script type="dojo/on" data-dojo-event="submit">
        dojo.require("dojo.NodeList-manipulate");
        var items = grid2.selection.getSelected();
        if(items.length){            
            dojo.forEach(items, function(selectedItem){
                if(selectedItem !== null){
                    attribute = 'idpersonne';
                    var value = grid2.store.getValues(selectedItem, attribute);                    
                    var idpersonne = dojo.query("#id").val(value);
                } 
            }); 
        }
    </script>

    <input type="hidden" id="id" name="id"  value="" />
    <button data-dojo-type="dijit/form/Button"             
            type="submit" onClick="myDialog.show();" >
        Modifier
    </button>

    <button data-dojo-type="dijit/form/Button"             
            type="button">
        Supprimer
        <script type="dojo/method" data-dojo-event="onClick" data-dojo-args="evt">
            require(["dijit/registry"], function(registry){
            registry.byId("dialog").show();
            });
        </script>
    </button>

    <div id="dialog" title="Suppression" data-dojo-id="dialog" data-dojo-type="dijit/Dialog">
        <script type="dojo/on" data-dojo-event="show">
            
            dojo.require("dojo.NodeList-manipulate");
            var items = grid2.selection.getSelected();
            if(items.length){            
                dojo.forEach(items, function(selectedItem){
                    if(selectedItem !== null){
                        var idpersonne = grid2.store.getValues(selectedItem, 'idpersonne');
                        dojo.query("#idpersonne").val(idpersonne);
                        var nom = grid2.store.getValues(selectedItem, 'nom');
                        var prenom = grid2.store.getValues(selectedItem, 'prenom');
                        var detaille = prenom + ' ' + nom;
                        //domConst.place(prenom + ' ' + nom, "detaille");
                        alert(detaille);
                    } 
                }); 
            }
        </script>
        <p>Êtes-vous sûr de vouloir supprimer 
        <div id="detaille"></div>
        </p>
        <form action="<?php echo $this->url(array('action' => 'supprimer')); ?>" method="post">
            <div>
                <input type="hidden" id ="idpersonne" name="idpersonne" value="" />
                <button data-dojo-type="dijit/form/Button"  type="submit" name="supprimer">
                    Oui
                </button>
                <button data-dojo-type="dijit/form/Button" 
                        type="button" data-dojo-props="onClick:function(){dialog.hide();}"
                        id="cancel" >Non</button>
            </div>
        </form>
    </div>
</div>


<?php
echo $this->contentPane()->captureEnd('tab1');
echo $this->tabContainer()->captureEnd('tabcontainer');
?>



