<?php
$this->title = 'Les Communes';
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller' => 'commune', 'action' => 'ajouter')); ?>">Ajouter une nouvelle commune</a></p>
<table>
    <tr>
        <th>Nom</th>
        <th>Label</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($this->communes as $commune) : ?>
        <tr>
            <td><?php echo $this->escape($commune->nom);  ?></td>
            <td><?php echo $this->escape($commune->label);  ?></td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'commune', 'action' => 'modifier', 'id' => $commune->idcommune));  ?>">Modifier</a>
                <a href="<?php echo $this->url(array('controller' => 'commune', 'action' => 'supprimer', 'id' => $commune->idcommune));  ?>">Supprimer</a>
            </td>
        </tr>
<?php endforeach; ?>
</table>
