<?php

$this->title = 'Les Communes';
$this->headTitle($this->title);
?>
<?php

$this->tabContainer()->captureStart('tabcontainer', array(), array('style' => 'width:1000px;height:300px;'));
$this->contentPane()->captureStart('tab1', array(), array('title' => 'User Manager'));
?>
<p><a href="<?php echo $this->url(array('controller'=>'commune',
        'action'=>'ajouter'));?>">Ajouter une nouvelle Commune</a></p>
<script type="text/javascript" >    
    var structure = [ 
        { field: 'idcommune', name: 'CommuneID', width: '50px' },
        { field: 'nom', name : 'Nom', width: '100px' },
        { field: 'label', name : 'Label', width: '200px'}
    ]; 
</script>

<span dojoType="dojox.data.QueryReadStore" jsId="idcommune" url="/v_esp/public/commune/indexjson"></span>
<div id="grid1" dojoType="dojox.grid.DataGrid" store="idcommune" structure="structure"></div>

<?php

echo $this->contentPane()->captureEnd('tab1');
echo $this->tabContainer()->captureEnd('tabcontainer');
?>
