<?php
$this->title = 'Les Douare';
$this->headTitle($this->title);

?>



<?php

$this->tabContainer()->captureStart('tabcontainer', array(), array());
$this->contentPane()->captureStart('tab1', array(), array('title' => 'User Manager'));
?>
<p><a href="<?php echo $this->url(array('controller'=>'douare',
        'action'=>'ajouter'));?>">Ajouter un nouveau douare</a></p>
<script type="text/javascript" >    
    var structure = [ 
        { field: 'iddouare', name: 'CommuneID', width: '50px' },
        { field: 'nom', name : 'Nom', width: '100px' },
        { field: 'label', name : 'Label', width: '100px'},
        { field: 'gps_alt', name : 'Gps Alt', width: '50px' },
        { field: 'gps_lan', name : 'Gps Lan', width: '50px' },
        { field: 'commune_idcommune', name : 'commune', width: '50px' }
    ]; 
</script>


<span dojoType="dojox.data.QueryReadStore" jsId="iddouare" url="douare/indexjson"></span>
<div id="grid1" data-dojo-id="grid2" dojoType="dojox.grid.DataGrid" 
     data-dojo-props="store:iddouare,
     structure:'structure'  ,
     clientSort:true,
     rowSelector:'20px'"
     style=" height: 260px;"></div>
     
<div data-dojo-type="dijit/form/Form" id="modifier" data-dojo-id="myForm"
     encType="multipart/form-data" action="douare/modifier" method="GET">
    <script type="dojo/on" data-dojo-event="submit">
        dojo.require("dojo.NodeList-manipulate");
        var items = grid2.selection.getSelected();
        if(items.length){            
            dojo.forEach(items, function(selectedItem){
                if(selectedItem !== null){
                    attribute = 'iddouare';
                    var value = grid2.store.getValues(selectedItem, attribute);                    
                    var iddouare = dojo.query("#id").val(value);
                } 
            }); 
        }
        dojo.byId("modifier").appendChild(u.domNode);
    </script>

    <input type="hidden" id="id" name="id"  value="" />
    <button data-dojo-type="dijit/form/Button"             
            type="submit" >
        Modifier
    </button>

    <button data-dojo-type="dijit/form/Button"             
            type="button">
        Supprimer
        <script type="dojo/method" data-dojo-event="onClick" data-dojo-args="evt">
            require(["dijit/registry"], function(registry){
            registry.byId("dialog").show();
            });
        </script>
    </button>

    <div id="dialog" title="Suppression" data-dojo-id="dialog" data-dojo-type="dijit/Dialog">
        <script type="dojo/on" data-dojo-event="show">            
            dojo.require("dojo.NodeList-manipulate");
            var items = grid2.selection.getSelected();
            if(items.length){            
                dojo.forEach(items, function(selectedItem){
                    if(selectedItem !== null){
                        var iddouare = grid2.store.getValues(selectedItem, 'iddouare');
                        dojo.query("#iddouare").val(iddouare);
                        var detaille = ' '+grid2.store.getValues(selectedItem, 'label');
                        dojo.query("#detaille").html(detaille);                      
                    } 
                }); 
            }
        </script>
        <p>Êtes-vous sûr de vouloir supprimer <div id="detaille"></div>
        </p>
        <form action="<?php echo $this->url(array('action' => 'supprimer')); ?>" method="post">
            <div>
                <input type="hidden" id ="iddouare" name="iddouare" value="" />
                <button data-dojo-type="dijit/form/Button"  type="submit" name="supprimer" value="Oui">
                    Oui
                </button>
                <button data-dojo-type="dijit/form/Button" 
                        type="button" data-dojo-props="onClick:function(){dialog.hide();}"
                        id="cancel" >Non</button>
            </div>
        </form>
    </div>
</div>
<?php

echo $this->contentPane()->captureEnd('tab1');
echo $this->tabContainer()->captureEnd('tabcontainer');
?>


