


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Wood Working   
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20110708

-->
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Voyage Espoire');


echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css'); ?>



        <?php
        Zend_Dojo::enableView($this);


        if ($this->dojo()->isEnabled()) {
            $this->dojo()->setLocalPath($this->baseUrl() . '/js/dojo/dojo.js')
                    ->addStyleSheetModule('dijit.themes.tundra');

            echo $this->dojo();

            echo $this->headScript();
        }
        ?>




    </head>
    <body  class="tundra">
        <body>

            <?php
            $this->borderContainer()->captureStart('masterLayout', array('design' => 'headline'));

            echo $this->contentPane(
                    'menuPane', $this->partial('menu.phtml'), array('region' => 'top'), array('style' => 'background-color: darkblue;')
            );

            echo $this->contentPane(
                    'navPane', $this->partial('nav.phtml'), array('region' => 'left'), array('style' => 'width: 200px; background-color: lightblue;')
            );

            echo $this->contentPane(
                    'mainPane', $this->layout()->content, array('title' => $this->escape($this->title), 'region' => 'center'), array('style' => 'background-color: white;')
            );

            echo $this->contentPane(
                    'statusPane', $this->partial('status.phtml'), array('region' => 'bottom'), array('style' => 'background-color: lightgray;')
            );

            echo $this->borderContainer()->captureEnd('masterLayout');
            ?>
        </body>
    </body>
</html>
