


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Wood Working   
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20110708

-->
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Voyage Espoire');
$this->addHelperPath('Zend/Dojo/View/Helper/', 'Zend_Dojo_View_Helper');


echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php
        echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css')
                ->appendStylesheet($this->baseUrl() . '/js/dojox/grid/resources/tundraGrid.css');
        ?>



        <?php echo $this->headScript(); ?>
        <?php
        if ($this->dojo()->isEnabled()) {
            $this->dojo()->setDjConfigOption('usePlainJson', true)
                    ->setLocalPath($this->baseUrl() . '/js/dojo/dojo.js')
                    ->addStyleSheetModule('dijit.themes.tundra');
            $this->dojo()->requireModule('dojox.data.QueryReadStore')->requireModule('dojox.grid.DataGrid');

            echo $this->dojo();




            echo $this->headScript();
        }
//        $this->headLink()->appendStylesheet($this->baseUrl() . '/js/dojox/grid/resources/tundraGrid.css');
        ?>











    </head>
    <body  class="tundra">

  <?php
//$this->tabContainer()->captureStart('main-container',
//                                    array('design' => 'headline'),
//                                    array(
//                                            'style'=>'height:400px;width:800px'
//                                     ));

      
        $this->borderContainer()->captureStart('masterLayout', array('design' => 'headline'));

        echo $this->contentPane(
                'menuPane', $this->partial('menu.phtml'), array('region' => 'top'), array('class' => 'menuPaneCss')
        );

//            $this->contentPane()->captureStart('centerLayout', array('class' => 'centerLayoutCss'));
        echo $this->contentPane(
                'navPane', $this->partial('nav.phtml'), array('region' => 'left'), array('class' => 'navPaneCss')
        );



       

        echo $this->contentPane(
                'mainPane', $this->layout()->content, array('title' => $this->escape($this->title), 'region' => 'right'), array('class' => 'mainPaneCss')
        );
        
//            $this->borderContainer()->captureEnd('centerLayout', array('class' => 'centerLayoutCss'));

        echo $this->contentPane(
                'statusPane', $this->partial('status.phtml'), array('region' => 'bottom'), array('class' => 'statusPaneCss')
        );

        echo $this->borderContainer()->captureEnd('masterLayout');
        
//        echo $this->tabContainer()->captureEnd('main-container');
?>
        ?>

    </body>
</html>
