<ul>
    <li class="current_page_item"><a href="<?php echo $this->baseUrl() ?>/index" >Homepage</a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/commune" >Commune</a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/douare" >Douare</a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/expedition">Expedition</a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/packtage">Packtage</a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/personne">Personne</a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/multimedia">Multimedia</a></li>
    <!--<li><a href="<?php echo $this->baseUrl() ?>/type">Type</a></li>-->
    <li><a href="#">Contact</a></li>

</ul>
